"use client";

import { FormEvent, useState } from "react";
import { db } from "../utils/firebase";
import { collection, addDoc } from "firebase/firestore";
import { useRouter } from "next/navigation";
import { DB_COLLECTION, generateGameboard } from "../utils/board";

const StartGame = () => {
  const [name, setName] = useState("");
  const [loading, setLoading] = useState(false);
  const [gridSize, setGridSize] = useState("5x5");
  const router = useRouter();

  // Create a new game
  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    // Prevent empty name
    if (name == "") {
      return;
    }

    setLoading(true);

    // Get grid dimension numbers from string
    const [gridWidth, gridHeight] = gridSize.split("x").map((i) => Number(i));

    // Set up game data
    const gameData: Game = {
      players: [
        {
          id: "abc",
          name,
        },
      ],
      gameboard: generateGameboard(gridWidth, gridHeight),
      gridWidth,
      gridHeight,
      status: "waiting",
    };

    // Sent data to Firebase
    await addDoc(collection(db, DB_COLLECTION), gameData)
      .then((docRef) => {
        // Navigate to id generated by Firebase
        router.push("/" + docRef.id);
      })
      .catch((e) => {
        setLoading(false);
      });
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={name}
          onChange={(e: any) => setName(e.target.value)}
          disabled={loading}
          maxLength={10}
        />

        <button type="submit" disabled={loading}>
          {loading ? "Loading..." : "Start game"}
        </button>
      </form>
    </div>
  );
};

export default StartGame;
